// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: picture_service.proto

package backend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePictureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlbumId int32    `protobuf:"varint,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags    []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Data    []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreatePictureRequest) Reset() {
	*x = CreatePictureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePictureRequest) ProtoMessage() {}

func (x *CreatePictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePictureRequest.ProtoReflect.Descriptor instead.
func (*CreatePictureRequest) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePictureRequest) GetAlbumId() int32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

func (x *CreatePictureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePictureRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreatePictureRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreatePictureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pictures *PictureMessage `protobuf:"bytes,1,opt,name=pictures,proto3" json:"pictures,omitempty"`
}

func (x *CreatePictureResponse) Reset() {
	*x = CreatePictureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePictureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePictureResponse) ProtoMessage() {}

func (x *CreatePictureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePictureResponse.ProtoReflect.Descriptor instead.
func (*CreatePictureResponse) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePictureResponse) GetPictures() *PictureMessage {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type UpdatePictureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pictures *PictureMessage `protobuf:"bytes,1,opt,name=pictures,proto3" json:"pictures,omitempty"`
}

func (x *UpdatePictureRequest) Reset() {
	*x = UpdatePictureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePictureRequest) ProtoMessage() {}

func (x *UpdatePictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePictureRequest.ProtoReflect.Descriptor instead.
func (*UpdatePictureRequest) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePictureRequest) GetPictures() *PictureMessage {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type UpdatePictureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pictures *PictureMessage `protobuf:"bytes,1,opt,name=pictures,proto3" json:"pictures,omitempty"`
}

func (x *UpdatePictureResponse) Reset() {
	*x = UpdatePictureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePictureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePictureResponse) ProtoMessage() {}

func (x *UpdatePictureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePictureResponse.ProtoReflect.Descriptor instead.
func (*UpdatePictureResponse) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePictureResponse) GetPictures() *PictureMessage {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type DeletePictureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PictureId int32 `protobuf:"varint,1,opt,name=picture_id,json=pictureId,proto3" json:"picture_id,omitempty"`
}

func (x *DeletePictureRequest) Reset() {
	*x = DeletePictureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePictureRequest) ProtoMessage() {}

func (x *DeletePictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePictureRequest.ProtoReflect.Descriptor instead.
func (*DeletePictureRequest) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePictureRequest) GetPictureId() int32 {
	if x != nil {
		return x.PictureId
	}
	return 0
}

type DeletePictureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    int32           `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Pictures *PictureMessage `protobuf:"bytes,2,opt,name=pictures,proto3" json:"pictures,omitempty"`
}

func (x *DeletePictureResponse) Reset() {
	*x = DeletePictureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePictureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePictureResponse) ProtoMessage() {}

func (x *DeletePictureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePictureResponse.ProtoReflect.Descriptor instead.
func (*DeletePictureResponse) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePictureResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DeletePictureResponse) GetPictures() *PictureMessage {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type ListPicturesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPicturesRequest) Reset() {
	*x = ListPicturesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPicturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPicturesRequest) ProtoMessage() {}

func (x *ListPicturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPicturesRequest.ProtoReflect.Descriptor instead.
func (*ListPicturesRequest) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{6}
}

type ListPicturesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    int32           `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Pictures *PictureMessage `protobuf:"bytes,2,opt,name=pictures,proto3" json:"pictures,omitempty"`
}

func (x *ListPicturesResponse) Reset() {
	*x = ListPicturesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPicturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPicturesResponse) ProtoMessage() {}

func (x *ListPicturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPicturesResponse.ProtoReflect.Descriptor instead.
func (*ListPicturesResponse) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListPicturesResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ListPicturesResponse) GetPictures() *PictureMessage {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type ListAlbumPicturesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAlbumPicturesRequest) Reset() {
	*x = ListAlbumPicturesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAlbumPicturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlbumPicturesRequest) ProtoMessage() {}

func (x *ListAlbumPicturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlbumPicturesRequest.ProtoReflect.Descriptor instead.
func (*ListAlbumPicturesRequest) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{8}
}

type ListAlbumPicturesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    int32           `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Pictures *PictureMessage `protobuf:"bytes,2,opt,name=pictures,proto3" json:"pictures,omitempty"`
}

func (x *ListAlbumPicturesResponse) Reset() {
	*x = ListAlbumPicturesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAlbumPicturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlbumPicturesResponse) ProtoMessage() {}

func (x *ListAlbumPicturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlbumPicturesResponse.ProtoReflect.Descriptor instead.
func (*ListAlbumPicturesResponse) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListAlbumPicturesResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ListAlbumPicturesResponse) GetPictures() *PictureMessage {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type SearchPicturesByTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *SearchPicturesByTagRequest) Reset() {
	*x = SearchPicturesByTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPicturesByTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPicturesByTagRequest) ProtoMessage() {}

func (x *SearchPicturesByTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPicturesByTagRequest.ProtoReflect.Descriptor instead.
func (*SearchPicturesByTagRequest) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{10}
}

func (x *SearchPicturesByTagRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchPicturesByTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pictures []*PictureMessage `protobuf:"bytes,1,rep,name=pictures,proto3" json:"pictures,omitempty"`
}

func (x *SearchPicturesByTagResponse) Reset() {
	*x = SearchPicturesByTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPicturesByTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPicturesByTagResponse) ProtoMessage() {}

func (x *SearchPicturesByTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPicturesByTagResponse.ProtoReflect.Descriptor instead.
func (*SearchPicturesByTagResponse) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{11}
}

func (x *SearchPicturesByTagResponse) GetPictures() []*PictureMessage {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type SearchPicturesByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *SearchPicturesByNameRequest) Reset() {
	*x = SearchPicturesByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPicturesByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPicturesByNameRequest) ProtoMessage() {}

func (x *SearchPicturesByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPicturesByNameRequest.ProtoReflect.Descriptor instead.
func (*SearchPicturesByNameRequest) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{12}
}

func (x *SearchPicturesByNameRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchPicturesByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pictures []*PictureMessage `protobuf:"bytes,1,rep,name=pictures,proto3" json:"pictures,omitempty"`
}

func (x *SearchPicturesByNameResponse) Reset() {
	*x = SearchPicturesByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPicturesByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPicturesByNameResponse) ProtoMessage() {}

func (x *SearchPicturesByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPicturesByNameResponse.ProtoReflect.Descriptor instead.
func (*SearchPicturesByNameResponse) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{13}
}

func (x *SearchPicturesByNameResponse) GetPictures() []*PictureMessage {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type PictureMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageId   int32    `protobuf:"varint,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Data      []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Tags      []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Name      string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	AlbumId   int32    `protobuf:"varint,5,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	OwnerName string   `protobuf:"bytes,6,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
}

func (x *PictureMessage) Reset() {
	*x = PictureMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PictureMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureMessage) ProtoMessage() {}

func (x *PictureMessage) ProtoReflect() protoreflect.Message {
	mi := &file_picture_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureMessage.ProtoReflect.Descriptor instead.
func (*PictureMessage) Descriptor() ([]byte, []int) {
	return file_picture_service_proto_rawDescGZIP(), []int{14}
}

func (x *PictureMessage) GetImageId() int32 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *PictureMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PictureMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PictureMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PictureMessage) GetAlbumId() int32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

func (x *PictureMessage) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

var File_picture_service_proto protoreflect.FileDescriptor

var file_picture_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x44, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2b, 0x0a, 0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x43, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x22, 0x44, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x70, 0x69,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x70,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x49, 0x64, 0x22, 0x5a,
	0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2b, 0x0a,
	0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x59, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x2b, 0x0a, 0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x1a, 0x0a, 0x18,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5e, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2b, 0x0a, 0x08, 0x70,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08,
	0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x32, 0x0a, 0x1a, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x4a, 0x0a, 0x1b,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x42, 0x79,
	0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x70,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08,
	0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x33, 0x0a, 0x1b, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x4b, 0x0a,
	0x1c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x42,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0xa1, 0x01, 0x0a, 0x0e, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x84,
	0x04, 0x0a, 0x0e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x15, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x15, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x15, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x12, 0x14, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x69,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x12, 0x4c, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x62, 0x75,
	0x6d, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x50,
	0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x42, 0x79, 0x54, 0x61, 0x67, 0x12, 0x1b, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x69,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x53, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x70, 0x69, 0x63, 0x73, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_picture_service_proto_rawDescOnce sync.Once
	file_picture_service_proto_rawDescData = file_picture_service_proto_rawDesc
)

func file_picture_service_proto_rawDescGZIP() []byte {
	file_picture_service_proto_rawDescOnce.Do(func() {
		file_picture_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_picture_service_proto_rawDescData)
	})
	return file_picture_service_proto_rawDescData
}

var file_picture_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_picture_service_proto_goTypes = []interface{}{
	(*CreatePictureRequest)(nil),         // 0: CreatePictureRequest
	(*CreatePictureResponse)(nil),        // 1: CreatePictureResponse
	(*UpdatePictureRequest)(nil),         // 2: UpdatePictureRequest
	(*UpdatePictureResponse)(nil),        // 3: UpdatePictureResponse
	(*DeletePictureRequest)(nil),         // 4: DeletePictureRequest
	(*DeletePictureResponse)(nil),        // 5: DeletePictureResponse
	(*ListPicturesRequest)(nil),          // 6: ListPicturesRequest
	(*ListPicturesResponse)(nil),         // 7: ListPicturesResponse
	(*ListAlbumPicturesRequest)(nil),     // 8: ListAlbumPicturesRequest
	(*ListAlbumPicturesResponse)(nil),    // 9: ListAlbumPicturesResponse
	(*SearchPicturesByTagRequest)(nil),   // 10: SearchPicturesByTagRequest
	(*SearchPicturesByTagResponse)(nil),  // 11: SearchPicturesByTagResponse
	(*SearchPicturesByNameRequest)(nil),  // 12: SearchPicturesByNameRequest
	(*SearchPicturesByNameResponse)(nil), // 13: SearchPicturesByNameResponse
	(*PictureMessage)(nil),               // 14: PictureMessage
}
var file_picture_service_proto_depIdxs = []int32{
	14, // 0: CreatePictureResponse.pictures:type_name -> PictureMessage
	14, // 1: UpdatePictureRequest.pictures:type_name -> PictureMessage
	14, // 2: UpdatePictureResponse.pictures:type_name -> PictureMessage
	14, // 3: DeletePictureResponse.pictures:type_name -> PictureMessage
	14, // 4: ListPicturesResponse.pictures:type_name -> PictureMessage
	14, // 5: ListAlbumPicturesResponse.pictures:type_name -> PictureMessage
	14, // 6: SearchPicturesByTagResponse.pictures:type_name -> PictureMessage
	14, // 7: SearchPicturesByNameResponse.pictures:type_name -> PictureMessage
	0,  // 8: PictureService.CreatePicture:input_type -> CreatePictureRequest
	2,  // 9: PictureService.UpdatePicture:input_type -> UpdatePictureRequest
	4,  // 10: PictureService.DeletePicture:input_type -> DeletePictureRequest
	6,  // 11: PictureService.ListPictures:input_type -> ListPicturesRequest
	8,  // 12: PictureService.ListAlbumPictures:input_type -> ListAlbumPicturesRequest
	10, // 13: PictureService.SearchPicturesByTag:input_type -> SearchPicturesByTagRequest
	12, // 14: PictureService.SearchPicturesByName:input_type -> SearchPicturesByNameRequest
	1,  // 15: PictureService.CreatePicture:output_type -> CreatePictureResponse
	3,  // 16: PictureService.UpdatePicture:output_type -> UpdatePictureResponse
	5,  // 17: PictureService.DeletePicture:output_type -> DeletePictureResponse
	7,  // 18: PictureService.ListPictures:output_type -> ListPicturesResponse
	9,  // 19: PictureService.ListAlbumPictures:output_type -> ListAlbumPicturesResponse
	11, // 20: PictureService.SearchPicturesByTag:output_type -> SearchPicturesByTagResponse
	13, // 21: PictureService.SearchPicturesByName:output_type -> SearchPicturesByNameResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_picture_service_proto_init() }
func file_picture_service_proto_init() {
	if File_picture_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_picture_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePictureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePictureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePictureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePictureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePictureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePictureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPicturesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPicturesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAlbumPicturesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAlbumPicturesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPicturesByTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPicturesByTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPicturesByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPicturesByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PictureMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_picture_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_picture_service_proto_goTypes,
		DependencyIndexes: file_picture_service_proto_depIdxs,
		MessageInfos:      file_picture_service_proto_msgTypes,
	}.Build()
	File_picture_service_proto = out.File
	file_picture_service_proto_rawDesc = nil
	file_picture_service_proto_goTypes = nil
	file_picture_service_proto_depIdxs = nil
}
